# -*- coding: utf-8 -*-
import entity.cards.LETL_015H
import entity.cards.LETL_006H
import entity.cards.LETL_007H
import entity.cards.LETL_002H
import entity.cards.LETL_014H
import entity.cards.LETL_009H
import entity.cards.LETL_010H
import entity.cards.LETL_011H
import entity.cards.LETL_012H
import entity.cards.LETL_016H
import entity.cards.LETL_003H
import entity.cards.LETL_005H
import entity.cards.LETL_001H
import entity.cards.LETL_019H
import entity.cards.LETL_020H
import entity.cards.LETL_021H
import entity.cards.LETL_028H
import entity.cards.LETL_029H
import entity.cards.LETL_030H
import entity.cards.LETL_031H
import entity.cards.LETL_032H
import entity.cards.LETL_033H
import entity.cards.LETL_034H
import entity.cards.LETL_036H
import entity.cards.LETL_022H
import entity.cards.LETL_017H
import entity.cards.LETL_026H
import entity.cards.LETL_027H
import entity.cards.LETL_038H
import entity.cards.LETL_037H
import entity.cards.LETL_039H
import entity.cards.LETL_040H
import entity.cards.BARL_025H
import entity.cards.BARL_013H
import entity.cards.BARL_002H
import entity.cards.BARL_024H
import entity.cards.BARL_012H
import entity.cards.BARL_023H
import entity.cards.BARL_008H
import entity.cards.BARL_009H
import entity.cards.BARL_010H
import entity.cards.BARL_005H
import entity.cards.BARL_007H
import entity.cards.BARL_017H
import entity.cards.BARL_016H
import entity.cards.BARL_015H
import entity.cards.SWL_10H
import entity.cards.SWL_13H
import entity.cards.SWL_06H
import entity.cards.SWL_25H
import entity.cards.SWL_01H
import entity.cards.LETL_041H
import entity.cards.SWL_14H
import entity.cards.SWL_26H
import entity.cards.LETLT_001
import entity.cards.LETLT_003
import entity.cards.LETLT_002
import entity.cards.LETLT_004
import entity.cards.LETLT_005
import entity.cards.LETLT_006
import entity.cards.LETLT_007
import entity.cards.LETLT_008
import entity.cards.LETLT_009
import entity.cards.LETLT_010
import entity.cards.LETLT_011
import entity.cards.LETLT_012
import entity.cards.LETLT_013
import entity.cards.LETLT_014
import entity.cards.LETLT_015
import entity.cards.LETLT_016
import entity.cards.LETLT_017
import entity.cards.LETLT_018
import entity.cards.LETLT_019
import entity.cards.LETLT_020
import entity.cards.LETLT_021
import entity.cards.LETLT_022
import entity.cards.LT21_05H
import entity.cards.LETL_
import entity.cards.LT21_03H
import entity.cards.LT21_01H
import entity.cards.LETLT_033
import entity.cards.LETLT_036
import entity.cards.LETLT_032
import entity.cards.LETLT_031
import entity.cards.LETLT_034
import entity.cards.LETLT_035
import entity.cards.LETLT_044
import entity.cards.LETLT_045
import entity.cards.LETLT_023
import entity.cards.LETLT_025
import entity.cards.LETLT_027
import entity.cards.LETLT_029
import entity.cards.LETLT_030
import entity.cards.LETLT_037
import entity.cards.LETLT_038
import entity.cards.LETLT_039
import entity.cards.LETLT_040
import entity.cards.LETLT_041
import entity.cards.LETLT_042
import entity.cards.LETLT_043
import entity.cards.LETLT_048
import entity.cards.LETLT_050
import entity.cards.LETLT_051
import entity.cards.LETLT_052
import entity.cards.LETLT_053
import entity.cards.LETLT_054
import entity.cards.LETLT_055
import entity.cards.LETLT_056
import entity.cards.LETLT_057
import entity.cards.LETLT_058
import entity.cards.LETLT_059
import entity.cards.LETLT_060
import entity.cards.LETLT_061
import entity.cards.LETLT_070
import entity.cards.LETLT_071
import entity.cards.LETLT_072
import entity.cards.LETLT_073
import entity.cards.LETLT_074
import entity.cards.LETLT_075
import entity.cards.LETLT_076
import entity.cards.LETLT_077
import entity.cards.LETLT_080
import entity.cards.LETLT_081
import entity.cards.LETLT_082
import entity.cards.LETLT_083
import entity.cards.LETLT_084
import entity.cards.LETLT_085
import entity.cards.LETLT_086
import entity.cards.LETLT_087
import entity.cards.LETLT_090
import entity.cards.LETLT_091
import entity.cards.LETLT_088
import entity.cards.LETLT_082
import entity.cards.LETL_9
import entity.cards.LETL_024H
import entity.cards.LT21_04H
import entity.cards.LETL_
